### ISSUE TITLE
Appreciate your hobby

### ISSUE THREAD

**Issue by lebedynskyi** [shnok/unity-mmo-server#23]
I was looking for some modern MMORPG server to check how should it work and get some more info about server architecture.

10 years ago I was inspired by L2j and i become a software engeneer.  Unfortunatelly i am not related to beckend. So i decided to make a server as my hobby.  You can find it here - https://github.com/lebedynskyi/L2Server

I was double surprised when i saw your gitlab L2 unity project.. 
And I dissapointed about your server architecture. You just did almost the same as it was 20 years ago in l2j.

Al your logic is inside Packet. And it will be a problem of duplicating the code for validations and condirions. I moved everything to different layers. But Seems i have similar issue. Thats why i wanted to find some modern MMORPG server.

Keep growing. Keep your development. Good luck.

**Comment by shnok** [comment]
Hi, yes indeed, I'm following more or less the L2J architecture. I'm not familiar with server and multiplayer development. So following L2J project makes me save time and this project is reliable as it has been working for years and was made for L2. 

My plan is not making a new revolutional or fully optimized server. I'm just doing this as a hobby and to learn or it's done (or was done). 

It would take me years to implement all the L2 classes and features into unity so scalability/optimization of the network is not very important.

Thank you for showing interest into the project.
